name: Tests

on: pull_request

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run tests
        shell: python
        run: |
          import os
          
          path = "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\pytest-of-runneradmin\\pytest-0\\test_parse_pip_requirements_wi1\\requirements1.txt"
          print(os.path.join(path, path))
          
