name: Tests

on: pull_request

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run tests
        shell: python
        run: |
          import os
          import shlex
          
          path = "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\pytest-of-runneradmin\\pytest-0\\test_parse_pip_requirements_wi1\\requirements1.txt"
          print(shlex.split(path))
          print(shlex.split("C:\\Users\\me\\path\\to\\file"))
          print(os.path.join(os.path.dirname(path), path))

  windows-req:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install requirements
        run: |
          echo pandas > req1.txt
          echo "-r $(pwd)\req.txt" > req2.txt
          cat req1.txt
          cat req2.txt
          pip install -r "$(pwd)\req2.txt"
